### ISSUE TITLE
uhm what

### ISSUE THREAD

**Issue by user0-07161** [orca-pet3910/orca-pet3910.github.io#3]
![image](https://github.com/user-attachments/assets/87a8dc73-bcfe-4946-ab02-7cc9dae7c7da)
this thing says "this is the url" but after that there's nothing

**Comment by orca-pet3910** [comment]
yeah that's because i suck at javascript

**Comment by user0-07161** [comment]
oh umm ok

**Comment by user0-07161** [comment]
ok lemme close this

**Comment by user0-07161** [comment]
nvm i think i can fix it

**Comment by orca-pet3910** [comment]
alr go ahead

**Comment by user0-07161** [comment]
> nvm i think i can fix it

okay umm nevermind!

**Comment by user0-07161** [comment]
sorry

**Comment by orca-pet3910** [comment]
it's okay
